export { default as GlobalStyle } from "./GlobalStyle"
export { default as SplashScreen } from "./SplashScreen"
export { default as NavBar } from "./NavBar"
export { default as Hero } from "./Hero"
export { default as About } from "./About"
export { default as Projects } from "./Projects"
export { default as Contact } from "./Contact"
export { default as Footer } from "./Footer"